-- Sample FAQ set for the demo client (fictional "Nordic Tea Co."). Idempotent: safe to re-run.
INSERT INTO faqs (category, question, answer) VALUES
('Shipping', 'How long does delivery take?',
 'Orders ship within 1–2 business days. Delivery takes 2–4 business days in the EU, 3–5 in the UK and 5–9 in the US.'),
('Shipping', 'Which countries do you ship to?',
 'We ship to all EU countries, the UK and the US. We do not ship anywhere else at the moment.'),
('Shipping', 'How much is shipping?',
 'Shipping is €4.90 within the EU, €6.90 to the UK and €9.90 to the US. Orders over €50 (EU/UK) or €80 (US) ship free.'),
('Shipping', 'Do you offer express shipping?',
 'Yes. Express (1–2 business days in the EU, 2–3 to the UK) costs an extra €7.00 and can be selected at checkout. It is not available to the US.'),
('Shipping', 'Do I have to pay customs or import duties?',
 'EU orders have no extra duties. UK and US orders may be charged import VAT or duties by local customs; these are not included in our prices and are paid by the customer.'),
('Orders', 'Where is my order?',
 'Once your order ships you receive an email with a tracking link. Tracking can take up to 24 hours to update. If you have not received a shipping email within 3 business days of ordering, please contact us with your order number.'),
('Orders', 'Can I change or cancel my order?',
 'You can change or cancel an order within 2 hours of placing it, as long as it has not shipped. After that please contact us and we will do our best, but we cannot guarantee it.'),
('Orders', 'Can I change my delivery address after ordering?',
 'Only before the order ships. Contact us as soon as possible with your order number and the new address.'),
('Orders', 'I received the wrong or a damaged item. What should I do?',
 'We are sorry about that! Please contact us within 14 days with your order number and a photo of the item, and we will send a replacement or refund you at no cost.'),
('Returns', 'What is your return policy?',
 'You can return unopened products within 30 days of delivery for a full refund of the item price. Opened tea cannot be returned for hygiene reasons unless it is defective.'),
('Returns', 'How do I start a return?',
 'Contact us with your order number and we will email you a return label. Refunds are issued to the original payment method within 5–7 business days after we receive the parcel.'),
('Returns', 'Who pays for return shipping?',
 'We pay for return shipping if the item is wrong or defective. For other returns the customer covers the return shipping cost.'),
('Payment', 'Which payment methods do you accept?',
 'We accept Visa, Mastercard, American Express, PayPal, Apple Pay and Google Pay.'),
('Payment', 'Do you offer discount codes or a newsletter discount?',
 'Yes, new subscribers get 10% off their first order when signing up to our newsletter. Discount codes cannot be combined and do not apply to gift cards.'),
('Payment', 'Can I get an invoice?',
 'An invoice is attached to your order confirmation email. If you need it with a VAT number or a company name, contact us with your order number.'),
('Products', 'How should I brew black tea?',
 'Use 1 teaspoon (about 2.5 g) per 200 ml of water at 95–100 °C and steep for 3–5 minutes.'),
('Products', 'How should I brew green tea?',
 'Use 1 teaspoon (about 2 g) per 200 ml of water at 75–80 °C and steep for 2–3 minutes. Hotter water makes green tea bitter.'),
('Products', 'How should I brew herbal tea?',
 'Use 1–2 teaspoons per 200 ml of freshly boiled water and steep for 5–7 minutes.'),
('Products', 'Is your tea organic?',
 'Most of our range is certified organic; products that are organic are marked with the EU organic logo on the product page.'),
('Products', 'How much caffeine does your tea contain?',
 'Black tea contains roughly 40–60 mg of caffeine per cup, green tea 20–40 mg, and our herbal blends are caffeine-free unless they contain mate or green tea (this is stated on the product page).'),
('Products', 'Do your teas contain allergens?',
 'Allergens are listed on each product page. Our facility also handles nuts and some blends contain nut-derived flavourings, so please check the label if you have an allergy. We cannot give medical advice.'),
('Products', 'How long does tea stay fresh?',
 'Unopened, our teas keep for 12–24 months (see the best-before date on the pack). Once opened, store in a cool, dry place away from light and finish within 6 months for the best flavour.'),
('Account', 'How do I reset my password?',
 'Click "Log in" on the website, then "Forgot your password?" and enter your email. You will receive a reset link within a few minutes; check your spam folder if it does not arrive.'),
('Contact', 'How can I contact customer support?',
 'You can email support@nordictea.example. We reply within 1 business day, Monday to Friday, 9:00–17:00 CET.'),
('Gifts', 'Do you sell gift cards?',
 'Yes, digital gift cards from €15 to €100 are available on the website and are delivered by email instantly. They are valid for 12 months.')
ON CONFLICT (question) DO UPDATE
SET category = EXCLUDED.category, answer = EXCLUDED.answer, updated_at = now();
